name: Android CI

# 触发器
on:
  push:
    tags:
      - v*
  pull_request:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-22.04
  
    steps:
      - uses: actions/checkout@v3
      - name: set-on JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          
      - name: Build Debug .apk
        run: |
          # Build the launcher
          gradle :H2CO3:assembleDebug

    
      - name: Get Version Name
        id: get-version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: H2CO3-debug
          path: H2CO3/build/outputs/apk/debug/*.apk
