name: Android CI

on:
  workflow_dispatch:
  push:
    tags:
      - v*
  pull_request:
    tags:
      - v*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set-on JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'dragonwell'
          cache: gradle

      - name: Build Debug .apk
        run: |
          # Build the launcher
          gradle :H2CO3:assembleDebug

      - name: Get Version Name
        id: get-version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: H2CO3-debug
          path: H2CO3/build/outputs/apk/debug/*.apk