name: Android CI

on:
  push:
    branches: [ H2CO3_main ]  # 当有代码推送到 H2CO3_main 分支时触发工作流程
  pull_request:
    branches: [ H2CO3_main ]  # 当有拉取请求到 H2CO3_main 分支时触发工作流程

jobs:
  build:

    runs-on: ubuntu-22.04  # 在 Ubuntu 22.04 环境上运行工作流程

    steps:
      - uses: actions/checkout@v3  # 使用 GitHub 提供的 checkout 动作，用于检出代码仓库
      - name: set-on JDK 17  # 设置 JDK 17 环境
        uses: actions/setup-java@v3  # 使用 GitHub 提供的 setup-java 动作，用于设置 Java 环境
        with:
          java-version: '17'  # 设置 Java 版本为 17
          distribution: 'temurin'  # 使用 Temurin 发行版
          cache: gradle  # 缓存 Gradle

      - name: Gradle Building...  # 执行 Gradle 构建
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1.1
      - name: Build Debug .apk  # 构建 Debug APK
        run: |
          # Build the launcher
          gradle :H2CO3:assembleDebug  # 使用 Gradle 构建 H2CO3 模块的 Debug 版本
          mv /H2CO3/build/outputs/apk/debug/H2CO3-debug.apk out/H2CO3-debug.apk  # 将构建好的 APK 移动到 out 目录下
      - name: Upload APK  # 上传 APK
        uses: actions/upload-artifact@v3  # 使用 GitHub 提供的 upload-artifact 动作，用于上传构建产物
        with:
          name: H2CO3-debug  # 设置构建产物的名称为 app-debug
          path: out/H2CO3-debug.*  # 设置构建产物的路径为 out 目录下的 app-debug 文件