name: Android CI

# 触发器
on:
  push:
    tags:
      - v*
  pull_request:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-22.04
    # 设置jdk环境为1.8
    steps:
      - uses: actions/checkout@v3  # 使用 GitHub 提供的 checkout 动作，用于检出代码仓库
      - name: set-on JDK 17  # 设置 JDK 17 环境
        uses: actions/setup-java@v3  # 使用 GitHub 提供的 setup-java 动作，用于设置 Java 环境
        with:
          java-version: '17'  # 设置 Java 版本为 17
          distribution: 'temurin'  # 使用 Temurin 发行版
          cache: gradle  # 缓存 Gradle

      - name: Build LWJGL
        run: |
          # Build the launcher
               gradle :LWJGL:assemble
      # 打包
      - name: Build Debug .apk
        run: |
          # Build the launcher
          gradle :H2CO3:assembleDebug

      # 获取apk版本号
      - name: Get Version Name
        uses: actions/github-script@v3
        id: get-version
        with:
          script: |
            const str=process.env.GITHUB_REF;
            return str.substring(str.indexOf("v"));
          result-encoding: string
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: /H2CO3/build/outputs/apk/debug/H2CO3-debug.*