name: Android CI

on:
  push:
    branches: [ Material-You ]
  pull_request:
    branches: [ Material-You ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: set-on JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle Building...
        run: ./gradlew build
      - name: Build Debug .apk
        run: |
          # Build the launcher
          gradle :H2CO3:assembleDebug
          mv H2CO3/build/outputs/apk/debug/app-debug.apk out/app-debug.apk
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: out/app-debug.*